version: 2.1
workflows:
  main:
    jobs:
      - build-36
      - build-311

jobs:
  build-36: &build
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "setup.py" }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install requirements
          command: |
            python -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "setup.py" }}-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - run:
          name: Build
          command: |
            python setup.py bdist_wheel sdist --formats=gztar
      - run:
          name: Test
          command: |
            . venv/bin/activate
            pytest tests
      - store_artifacts:
          path: dist
  build-311:
    <<: *build
    docker:
      - image: cimg/python:3.11
